archives:
-
  format_overrides:
  - goos: windows
    format: zip
before:
  hooks:
    - go mod tidy
brews:
-
  dependencies:
  - go
  description: Terraform Provider Linter
  folder: Formula
  tap:
    owner: chnsz
    name: chnsz
  homepage: https://github.com/chnsz/tf-linter
  install: |
    bin.install "tflinter"
  test: |
    system "#{bin}/tflinter -V"
builds:
-
  env:
  - CGO_ENABLED=0
  - GOFLAGS=-mod=readonly
  goos:
  - darwin
  - windows
  - linux
  goarch:
  - amd64
  - 386
  ldflags:
    - '-s -w -X main.version={{.Version}} -X main.commit={{.Commit}}'
  main: ./cmd/tflinter

changelog:
  skip: true
dockers:
-
  build_flag_templates:
  - "--label=org.label-schema.schema-version=1.0"
  - "--label=org.label-schema.version={{.Version}}"
  - "--label=org.label-schema.name={{.ProjectName}}"
  image_templates:
  - 'hmbig2/tf-linter:{{ .Version }}'
  - 'hmbig2/tf-linter:{{ .Major }}.{{ .Minor }}'
  - 'hmbig2/tf-linter:latest'
milestones:
-
  close: true